version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  mysqldb_2:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD_2
      - MYSQL_DATABASE=$MYSQLDB_DATABASE_2
    ports:
      - $MYSQLDB_LOCAL_PORT_2:$MYSQLDB_DOCKER_PORT_2
    volumes:
      - db_2:/var/lib/mysql
  
  app:
    depends_on:
      - mysqldb
      - mysqldb_2
    build: .  
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - DB_HOST_2=mysqldb_2
      - DB_USER_2=$MYSQLDB_USER_2
      - DB_PASSWORD_2=$MYSQLDB_ROOT_PASSWORD_2
      - DB_NAME_2=$MYSQLDB_DATABASE_2
      - DB_PORT_2=$MYSQLDB_DOCKER_PORT_2
    stdin_open: true
    tty: true
    
volumes: 
  db:
  db_2: